### ISSUE TITLE
Failed to resolve com.afollestad:easyvideoplayer:0.2.10

### ISSUE THREAD

**Issue by saadnawaz1** [afollestad/easy-video-player#34]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Easy Video Player.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `0.2.10.0`
 
###### Reproduction Steps

1. Add compile 'com.afollestad:easyvideoplayer:0.2.10' in build.gradle
2. Compile

###### Expected Result
Compile should succeed

###### Actual Result
I get error failed to resolve compile 'com.afollestad:easyvideoplayer:0.2.10'

**Comment by afollestad** [comment]
I've had no issues with this.

You probably are not using the correct repository in Android Studio.

**Comment by OmarMohamedDev** [comment]
Same problem here

**Comment by pevah** [comment]
Hello, I am having the same issue. I have tried in my current project and also in a brand new project created in Android Studio which points to JCenter by default

**Comment by Murtaza0xFF** [comment]
Having the same issue.

**Comment by piyushgreedy** [comment]
Please tell how to resolve step by step. I am new to android

Error:(31, 13) Failed to resolve: com.afollestad:easyvideoplayer:0.2.10.0

**Comment by natig8x** [comment]
same problem

**Comment by OmarMohamedDev** [comment]
Solved just adding to the build.gradle of the **project** (not the one of the app) under the dependencies node the classpath to 'com.neenbedankt.gradle.plugins:android-apt:1.4' , that is where the repository is located (the issue is caused by the absence of cache of the repo, i read this solution in another ticket that was opened here).

To summarize, the build.gradle file in the root folder of the project should appear something like:

buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}

(not consider the other address, your app configuration could be different, just add 

**classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'**

in the dependecies node)

**Comment by natig8x** [comment]
thanks but i already had this for another dependency `'com.neenbedankt.gradle.plugins:android-apt:1.4'`. I also tried adding this 
```
mavenCentral()
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```
to my repositories but it didn't solve the problem

**Comment by piyushgreedy** [comment]
Its not working. Please help someone.

**Comment by qlehong** [comment]
repositories {
    jcenter()
    maven { url "https://dl.bintray.com/drummer-aidan/maven" }
}

add this to root, It's work for me
